[tool.pytest.ini_options]
deprecator_warnings = [
    # Format is `message regex:allowed occurrences`
    'error:I am an explicit warning:7',
    'error:Oh no! I am deprecated!:8',
]
filterwarnings = [
    "ignore::UserWarning",
    "once:I am an explicit warning:DeprecationWarning:",
]
